[package]
name = "unirique_node"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "node"
path = "src/main.rs"

[dependencies]
node = { path = "crates/node" }

[workspace]
resolver = "2"
members = [
    ".",
    "crates/wire",
    "crates/neighbors",
    "crates/catalog",
    "crates/torrents",
    "crates/protocol",
    "crates/node",
    "crates/main_address",
]
default-members = ["."]

[profile.release]
opt-level = "s"
